language: java
env: OPENEOS_TEST_LOGLEVEL=INFO
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cd external-dependencies && ./install.sh > /dev/null && cd .."
